import { ShoppingBag } from "iconoir-react-native";

const string = {
  welcome: {
    hello: "¿Hola buen día como estas?",
    welcomeHappy: "El campo te da la bienvenida desde tu celular",
    chat: "Puedes escribirnos y conversaremos un rato",
    registerNewUserA: "Regístrate hoy y recibe",
    registerNewUserB: "Descuentos en tus primeras órdenes",
    message: "Aplican para usuarios nuevos",
    tyc: "Aplican T&C",
    registrate: "Regístrate",
    // eslint-disable-next-line no-dupe-keys
    registerNewUserA: "Ya tengo cuenta ",
  },
  Signup: {
    hello: "Bienvenidos al campo",
    name: "Nombre y apellido",
    mail: "Email (correo electrónico)",
    cell: "Numero de celular",
    require: "Rellena los espacios para registrarte correctamente",
    message: "Aplican para usuarios nuevos",
    tyc: "Aplican T&C",
    registrate: "Regístrate",
    registerNewUserA: "Ya tengo cuenta ",
  },
  home: {
    search: "Buscar en el campo",
    near: "Fincas mas cerca de ti",
    select: "Selecciona tu vereda favorita",
    searchDistric: "Busca tu vereda",
    require: "Rellena los espacios para registrarte correctamente",
    message: "Aplican para usuarios nuevos",
    tyc: "Aplican T&C",
    registrate: "Regístrate",
    registerNewUserA: "Ya tengo cuenta ",
    favorito: "Favorito",
    cart: "Ver Carrito",
    Shopping: "Seguir Comprando",
    add: "Agregar mas productos",
    addCart: "Complementa tu carrito",
    summaey: "Resumen",
    AddCode: "Agrega código promocional",
    codes: "Códigos promocionales",
    apply: "Aplicar",
    subtotal: "Subtotal",
    delivery: "Domicilio",
    total: "Total",
    cash: "Pago en efectivo",
    // eslint-disable-next-line no-dupe-keys
    message:
      "Recuerda realizar el pago en efectivo al domiciliario con billetes de baja categoría",
    pay: "Realizar pago",
    noCartMessage: "No tienes ningún articulo en tu carro",
    new: "Inicia un carrito nuevo",
  },
  homeSeller: {
    ADD_PRODUCT: "Agregar Producto",
    PRODUCT_ADDED: "Producto agregado!",
    PRODUCT_NAME: "Nombre del Producto",
    CATEGORY: "Categoría",
    DESCRIPTION: "Descripción del Producto",
    PRICE: "Precio",
    STOCK: "Stock",
    CAMERA_PERMISSION: "Se necesita acceso a la cámara.",
    GALLERY_PERMISSION: "Se necesita acceso a la galería.",
  },
  alertAddProduct: {
    CAMERA_PERMISSION: "Se necesita acceso a la cámara.",
    GALLERY_PERMISSION: "Se necesita acceso a la galería.",
    PRODUCT_ADDED: "Producto agregado!",
  },
  App: {
    next: "Continuar",
    redy: "Iniciar",
    home: "Inicio",
    chat: "chat",
    account: "Cuenta",
  },
};

export default string;
